[package]
name = "ansi-cursor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ansi-parser = { git = "https://github.com/joseburgosguntin/ansi-parser" }
